### ISSUE TITLE
Extra comma when more than one minute and hour 0 (midnight)

### ISSUE THREAD

**Issue by mcallinder** [RedHogs/cron-parser#26]
When you specify more than one minute, or every minute, and the hour is 0 for midnight, an extra comma will be placed after the minutes:

5 0 * * *&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;At 0:05 AM
5,10 0 * * *&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;At 05 and 10 minutes past the hour, 
5,10 0 2 * *&nbsp;&nbsp;&nbsp;&nbsp;At 05 and 10 minutes past the hour, , on day 2 of the month
5/10 0 2 * *&nbsp;&nbsp;&nbsp;&nbsp;Every 10 minutes, , on day 2 of the month

**Comment by MCAllinder** [comment]
Same for seconds:

5,6 0 0 * * *          At 5 and 6 seconds past the minute
5,6 0 1 * * *          At 5 and 6 seconds past the minute, , at 1:00 AM

**Comment by grahamar** [comment]
Thanks I'll have a fix out for this today
