### ISSUE TITLE
Time part from cron expression does not respect Locales whereas hour-part is 0-23h, not AM/PM.

### ISSUE THREAD

**Issue by joaogac** [RedHogs/cron-parser#29]
Time part from cron expression does not respect Locales whereas hour-part is 0-23h, not AM/PM.

Like in Spanish locale the hour-part from the cron-expression "0 15 16 ? * MON-FRI" should be "En 16:15, lunes hasta viernes", not "En 4:15 PM, lunes hasta viernes".

**Comment by grahamar** [comment]
I've added support for 24 hour, but it's not based on the locale as user preferences vary wildly irregardless of locale and I'd prefer it be backwards compatible first. Users can now specify 24-hour preference via the Options.

I've stripped out the Portuguese localisation from your pull request and included it in the latest.

Sorry for the delay!

**Comment by lovepoem** [comment]
https://github.com/grahamar/cron-parser/issues/54
