### ISSUE TITLE
In expression "0 0,5,10,15,20,25,30,35,40,45,50,55 * ? * *" the readable string appends an unexpected comma "," before the "and" preposition

### ISSUE THREAD

**Issue by joaogac** [RedHogs/cron-parser#30]
The expression **`"0 0,5,10,15,20,25,30,35,40,45,50,55 * ? * *"`** 

becomes *"At 00, 05, 10, 15, 20, 25, 30, 35, 40, 45, 50, and 55 minutes past the hour"* (with a comma before the word "and"), 

instead of *"At 00, 05, 10, 15, 20, 25, 30, 35, 40, 45, 50 and 55 minutes past the hour"*

This is just an example. Happens for all expression with more than 3 elements in the cron part.

**Comment by popq** [comment]
It is called the Oxford Comma, and using it is generally a good thing. Some examples of why:
https://thewritepractice.com/why-you-need-to-be-using-oxford-commas/
http://uk.businessinsider.com/always-use-the-oxford-comma-2015-5?r=US&IR=T
http://www.grammarly.com/blog/2015/what-is-the-oxford-comma-and-why-do-people-care-so-much-about-it/
